version: 2.1

orbs:
  vulnachecka: philiptest/wsstestorb@1.0.3

workflows:
  test:
    jobs:
    - vulnachecka/scan:
        config_file_path: "wss-unified-agent.config" 
        commands_file_path: "install_commands.sh"
